branches:
    - master
    - auto
    - try

required: true
context: f25-primary

container:
    image: registry.fedoraproject.org/fedora:25
packages:
  - git

env:
    CFLAGS: '-fsanitize=undefined -fsanitize-undefined-trap-on-error -fsanitize=address -O2 -Wp,-D_FORTIFY_SOURCE=2'
    ASAN_OPTIONS: 'detect_leaks=0'  # Right now we're not fully clean, but this gets us use-after-free etc
    # TODO when we're doing leak checks: G_SLICE: "always-malloc"

tests:
  - ci/ci-commitmessage-submodules.sh
  - ci/build-check.sh

timeout: 30m

artifacts:
  - test-suite.log
---

inherit: true

context: f25-rust
packages:
  - cargo
env:
  CONFIGOPTS: '--enable-rust'

tests:
    - ci/build.sh
    - make check TESTS=tests/test-rollsum

---

inherit: true

context: f25-experimental-api
env:
  CONFIGOPTS: '--enable-experimental-api'

tests:
  - ci/build-check.sh

---

inherit: true
required: true

context: f25-curl-openssl

packages:
  - pkgconfig(libcurl)
  - pkgconfig(openssl)

env:
  CONFIGOPTS: "--with-curl --with-openssl"

tests:
  - ci/build-check.sh

---

inherit: false
branches:
    - master
    - auto
    - try

context: f25ah-insttest
required: false

cluster:
  hosts:
    - name: vmcheck
      distro: fedora/25/atomic
  container:
    image: registry.fedoraproject.org/fedora:25

# Copy the build from the container to the host; ideally down the line
# this is installing an RPM via https://github.com/jlebon/redhat-ci/issues/10
tests:
  - ci/build.sh
  - make install DESTDIR=$(pwd)/insttree
  - rsync -rl -e 'ssh -o User=root' . vmcheck:ostree/
  - ssh root@vmcheck './ostree/tests/installed/fah-prep.sh && ostree admin unlock && rsync -rlv ./ostree/insttree/usr/ /usr/ && ./ostree/tests/installed/run.sh'

---

inherit: false
branches:
    - master
    - auto
    - try

context: f25-flatpak
required: false

# This test case wants an "unprivileged container with bubblewrap",
# which we don't have right now; so just provision a VM and do a
# docker --privileged run.
host:
  distro: fedora/25/atomic
  specs:
    ram: 4096  # build-bundle is a static delta, which needs RAM right now

tests:
  - docker run --rm --privileged -v $(pwd):/srv/code registry.fedoraproject.org/fedora:25 /bin/sh -c "cd /srv/code && ./ci/flatpak.sh"

artifacts:
  - test-suite.log
