branches:
    - master
    - auto
    - try

required: true
context: f25-sanitizer

container:
    image: projectatomic/ostree-tester

packages:
  - libasan
  - git
  - coccinelle

env:
    CFLAGS: '-fsanitize=undefined -fsanitize-undefined-trap-on-error -fsanitize=address -O2 -Wp,-D_FORTIFY_SOURCE=2'
    ASAN_OPTIONS: 'detect_leaks=0'  # Right now we're not fully clean, but this gets us use-after-free etc
    # TODO when we're doing leak checks: G_SLICE: "always-malloc"

build:
    config-opts: >
      --prefix=/usr
      --libdir=/usr/lib64
      --enable-installed-tests=exclusive
      --enable-gtk-doc

# The g-d-t-r timeout is for test-pull-many.sh; if tweaking this,
# also be sure to change the other cases below
tests:
    - make syntax-check
    - ./tests/ci-commitmessage-submodules.sh
    - make check
    - /bin/sh -c 'gnome-desktop-testing-runner -p 0 --timeout $((10 * 60)) libostree/'

timeout: 30m

artifacts:
    - test-suite.log

---

inherit: true
required: true

context: f25-clang

env:
    CC: 'clang'
    CFLAGS: '-Werror=unused-variable'

tests:
artifacts:


---

inherit: true

context: f25-rust

packages:
  - cargo

build:
    config-opts: >
      --prefix=/usr
      --libdir=/usr/lib64
      --enable-gtk-doc
      --enable-rust

env:
    CC: 'gcc'

tests:
    - make check TESTS=tests/test-rollsum

artifacts:
  - test-suite.log
---

inherit: true

context: f25-experimental-api

build:
    config-opts: >
      --prefix=/usr
      --libdir=/usr/lib64
      --enable-gtk-doc
      --enable-experimental-api

env:
    CC: 'gcc'

tests:
    - make check
    - /bin/sh -c 'gnome-desktop-testing-runner -p 0 --timeout $((10 * 60)) libostree/'

artifacts:
  - test-suite.log
---

inherit: true
required: true

context: f25-curl-openssl

packages:
  - pkgconfig(libcurl)
  - pkgconfig(openssl)

build:
    config-opts: >
      --prefix=/usr
      --libdir=/usr/lib64
      --enable-installed-tests=exclusive
      --enable-gtk-doc
      --with-curl
      --with-openssl

tests:
  - make check
  - /bin/sh -c 'gnome-desktop-testing-runner -p 0 --timeout $((10 * 60)) libostree/'

artifacts:
  - test-suite.log

---

inherit: false
branches:
    - master
    - auto
    - try

context: f25ah-insttest
required: false

cluster:
  hosts:
    - name: vmcheck
      distro: fedora/25/atomic
  container:
    image: projectatomic/ostree-tester

build:
    config-opts: >
      --prefix=/usr
      --libdir=/usr/lib64
      --enable-gtk-doc

# Copy the build from the container to the host; ideally down the line
# this is installing an RPM via https://github.com/jlebon/redhat-ci/issues/10
tests:
  - make install DESTDIR=$(pwd)/insttree
  - rsync -rl -e 'ssh -o User=root' . vmcheck:ostree/
  - ssh root@vmcheck './ostree/tests/installed/fah-prep.sh && ostree admin unlock && rsync -rlv ./ostree/insttree/usr/ /usr/ && ./ostree/tests/installed/run.sh'

artifacts:
  - test-suite.log

---

inherit: false
branches:
    - master
    - auto
    - try

context: f25-flatpak
required: false

# This test case wants an "unprivileged container with bubblewrap",
# which we don't have right now; so just provision a VM and do a
# docker --privileged run.
host:
  distro: fedora/25/atomic
  specs:
    ram: 4096  # build-bundle is a static delta, which needs RAM right now

tests:
  - docker run --rm --privileged -v $(pwd):/srv/code registry.fedoraproject.org/fedora:25 /bin/sh -c "cd /srv/code && ./ci/flatpak.sh"

artifacts:
  - test-suite.log
