branches:
    - master
    - auto
    - try

container:
    image: projectatomic/ostree-tester

# XXX: we can wipe this off once a newer image is built with
# it already included
packages:
  - libubsan

env:
    CFLAGS: '-fsanitize=undefined'

build:
    config-opts: >
      --prefix=/usr
      --libdir=/usr/lib64
      --enable-installed-tests
      --enable-gtk-doc

tests:
    - make syntax-check
    - make check
    - gnome-desktop-testing-runner ostree
    - sudo --user=testuser gnome-desktop-testing-runner ostree

timeout: 30m

artifacts:
    - test-suite.log

---

inherit: true

# XXX: ditto
packages:
  - clang

context: Clang

env:
    CC: 'clang'
    CFLAGS: '-Werror=unused-variable'

tests:
artifacts:
