language: c
sudo: required

env:
  # debian has libsodium-dev, ubuntu doesn't in core at least
  - ci_docker=debian:buster-slim ci_distro=debian ci_suite=stretch ci_configopts="--with-ed25519-libsodium" ci_pkgs="libsodium-dev"
  - ci_docker=debian:buster-slim ci_distro=debian ci_suite=stretch ci_configopts="--with-curl --with-ed25519-libsodium --without-gpgme" ci_pkgs="libsodium-dev"
  - ci_docker=ubuntu:xenial ci_distro=ubuntu ci_suite=xenial
  - ci_docker=i386/ubuntu:bionic ci_distro=ubuntu ci_suite=bionic

script:
  - sudo ci/travis-install.sh
  - ci_parallel=2 ci_sudo=yes ci/travis-build.sh

notifications:
  email: false
